name = "web3-brotli"
compatibility_date = "2022-07-28"
type = "javascript"
zone_id = ""
account_id = ""
route = "cache.storage/*"
kv_namespaces = [
  { binding = "RTV", id = "", preview_id = "" },
  { binding = "CONFIG", id = "", preview_id = "" }
]


[wasm_modules]
BROTLI_WASM = 'node_modules/brotli-wasm/pkg.bundler/brotli_wasm_bg.wasm'

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"